AllCops:
  Exclude:
    - Gemfile
    - bin/**/*
    - lib/tasks/**/*.rake
    - db/**/*
    - config/**/*
    - script/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  Max: 99

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/AbcSize:
  Max: 25
