version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - .:/src
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:alpine
